services:
  backend:
    image: joaovitormedeiros/admin-financeiro-backend:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MODO_MOCK=false

  frontend:
    image: joaovitormedeiros/admin-financeiro-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - BACKEND_URL=http://localhost:3000
    depends_on:
      - backend
